language: java

jdk:
  - oraclejdk8
  - oraclejdk7

services: mysql

before_script:
  - mysql -e 'CREATE DATABASE json_formater;'
  - mysql json_formater < web/database.sql

script: 
  - mvn json_formater -f web/pom.xml

after_script:
  - mysql -e 'DROP DATABASE json_formater;'

after_success:
  - mvn -f web/pom.xml cobertura:cobertura coveralls:report
